#!/bin/sh
# Place this file inside .githooks directory.
# Make sure the file is executable: Run `chmod +x pre-comment`.
# Run `git config core.hooksPath .githooks`.
npx stylelint "./src/lib/css/**/*.pcss"